[features]
seeds = false
[programs.testnet]
auction = "G1cr8ubixaosck66PGR9wyyZbTsSzTnxRVhV4FYn5AqX"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "testnet"
wallet = "/home/user/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
